package bean;
// Generated 14/12/2024 11:25:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraProduto generated by hbm2java
 */
@Entity
@Table(name="compra_produto"
    ,catalog="db_joao_almeida"
)
public class CompraProduto  implements java.io.Serializable {


     private int idCompraProduto;
     private EmdProduto emdProduto;
     private JvlCompra jvlCompra;
     private BigDecimal valorUnit;
     private String quantidade;

    public CompraProduto() {
    }

	
    public CompraProduto(int idCompraProduto, EmdProduto emdProduto, JvlCompra jvlCompra) {
        this.idCompraProduto = idCompraProduto;
        this.emdProduto = emdProduto;
        this.jvlCompra = jvlCompra;
    }
    public CompraProduto(int idCompraProduto, EmdProduto emdProduto, JvlCompra jvlCompra, BigDecimal valorUnit, String quantidade) {
       this.idCompraProduto = idCompraProduto;
       this.emdProduto = emdProduto;
       this.jvlCompra = jvlCompra;
       this.valorUnit = valorUnit;
       this.quantidade = quantidade;
    }
   
     @Id 

    
    @Column(name="id_compra_produto", unique=true, nullable=false)
    public int getIdCompraProduto() {
        return this.idCompraProduto;
    }
    
    public void setIdCompraProduto(int idCompraProduto) {
        this.idCompraProduto = idCompraProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_produto", nullable=false)
    public EmdProduto getEmdProduto() {
        return this.emdProduto;
    }
    
    public void setEmdProduto(EmdProduto emdProduto) {
        this.emdProduto = emdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_compra", nullable=false)
    public JvlCompra getJvlCompra() {
        return this.jvlCompra;
    }
    
    public void setJvlCompra(JvlCompra jvlCompra) {
        this.jvlCompra = jvlCompra;
    }

    
    @Column(name="valor_unit", precision=10)
    public BigDecimal getValorUnit() {
        return this.valorUnit;
    }
    
    public void setValorUnit(BigDecimal valorUnit) {
        this.valorUnit = valorUnit;
    }

    
    @Column(name="quantidade", length=10)
    public String getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }




}


