package bean;
// Generated 15/12/2024 20:30:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmdCliente generated by hbm2java
 */
@Entity
@Table(name="emd_cliente"
    ,catalog="db_joao_almeida"
)
public class EmdCliente  implements java.io.Serializable {


     private Integer emdIdCliente;
     private String emdNome;
     private String emdSobrenome;
     private String emdEmail;
     private String emdTelefone;
     private String emdBairro;
     private String emdCidade;
     private String emdEstado;
     private String emdCep;
     private String emdPais;
     private Date emdDataNascimento;
     private String emdGenero;
     private String emdProfissao;
     private String emdRua;
     private String emdNumero;

    public EmdCliente() {
    }

	
    public EmdCliente(String emdNome, String emdEmail, String emdTelefone, String emdBairro, String emdCidade, String emdEstado, String emdCep, String emdPais, String emdGenero) {
        this.emdNome = emdNome;
        this.emdEmail = emdEmail;
        this.emdTelefone = emdTelefone;
        this.emdBairro = emdBairro;
        this.emdCidade = emdCidade;
        this.emdEstado = emdEstado;
        this.emdCep = emdCep;
        this.emdPais = emdPais;
        this.emdGenero = emdGenero;
    }
    public EmdCliente(String emdNome, String emdSobrenome, String emdEmail, String emdTelefone, String emdBairro, String emdCidade, String emdEstado, String emdCep, String emdPais, Date emdDataNascimento, String emdGenero, String emdProfissao, String emdRua, String emdNumero) {
       this.emdNome = emdNome;
       this.emdSobrenome = emdSobrenome;
       this.emdEmail = emdEmail;
       this.emdTelefone = emdTelefone;
       this.emdBairro = emdBairro;
       this.emdCidade = emdCidade;
       this.emdEstado = emdEstado;
       this.emdCep = emdCep;
       this.emdPais = emdPais;
       this.emdDataNascimento = emdDataNascimento;
       this.emdGenero = emdGenero;
       this.emdProfissao = emdProfissao;
       this.emdRua = emdRua;
       this.emdNumero = emdNumero;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="emd_id_cliente", unique=true, nullable=false)
    public Integer getEmdIdCliente() {
        return this.emdIdCliente;
    }
    
    public void setEmdIdCliente(Integer emdIdCliente) {
        this.emdIdCliente = emdIdCliente;
    }

    
    @Column(name="emd_nome", nullable=false, length=40)
    public String getEmdNome() {
        return this.emdNome;
    }
    
    public void setEmdNome(String emdNome) {
        this.emdNome = emdNome;
    }

    
    @Column(name="emd_sobrenome", length=60)
    public String getEmdSobrenome() {
        return this.emdSobrenome;
    }
    
    public void setEmdSobrenome(String emdSobrenome) {
        this.emdSobrenome = emdSobrenome;
    }

    
    @Column(name="emd_email", nullable=false, length=100)
    public String getEmdEmail() {
        return this.emdEmail;
    }
    
    public void setEmdEmail(String emdEmail) {
        this.emdEmail = emdEmail;
    }

    
    @Column(name="emd_telefone", nullable=false, length=20)
    public String getEmdTelefone() {
        return this.emdTelefone;
    }
    
    public void setEmdTelefone(String emdTelefone) {
        this.emdTelefone = emdTelefone;
    }

    
    @Column(name="emd_bairro", nullable=false, length=200)
    public String getEmdBairro() {
        return this.emdBairro;
    }
    
    public void setEmdBairro(String emdBairro) {
        this.emdBairro = emdBairro;
    }

    
    @Column(name="emd_cidade", nullable=false, length=50)
    public String getEmdCidade() {
        return this.emdCidade;
    }
    
    public void setEmdCidade(String emdCidade) {
        this.emdCidade = emdCidade;
    }

    
    @Column(name="emd_estado", nullable=false, length=2)
    public String getEmdEstado() {
        return this.emdEstado;
    }
    
    public void setEmdEstado(String emdEstado) {
        this.emdEstado = emdEstado;
    }

    
    @Column(name="emd_cep", nullable=false, length=10)
    public String getEmdCep() {
        return this.emdCep;
    }
    
    public void setEmdCep(String emdCep) {
        this.emdCep = emdCep;
    }

    
    @Column(name="emd_pais", nullable=false, length=50)
    public String getEmdPais() {
        return this.emdPais;
    }
    
    public void setEmdPais(String emdPais) {
        this.emdPais = emdPais;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="emd_data_nascimento", length=10)
    public Date getEmdDataNascimento() {
        return this.emdDataNascimento;
    }
    
    public void setEmdDataNascimento(Date emdDataNascimento) {
        this.emdDataNascimento = emdDataNascimento;
    }

    
    @Column(name="emd_genero", nullable=false, length=20)
    public String getEmdGenero() {
        return this.emdGenero;
    }
    
    public void setEmdGenero(String emdGenero) {
        this.emdGenero = emdGenero;
    }

    
    @Column(name="emd_profissao", length=50)
    public String getEmdProfissao() {
        return this.emdProfissao;
    }
    
    public void setEmdProfissao(String emdProfissao) {
        this.emdProfissao = emdProfissao;
    }

    
    @Column(name="emd_rua", length=45)
    public String getEmdRua() {
        return this.emdRua;
    }
    
    public void setEmdRua(String emdRua) {
        this.emdRua = emdRua;
    }

    
    @Column(name="emd_numero", length=45)
    public String getEmdNumero() {
        return this.emdNumero;
    }
    
    public void setEmdNumero(String emdNumero) {
        this.emdNumero = emdNumero;
    }

}


