package bean;
// Generated 07/12/2024 15:09:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmdCategoria generated by hbm2java
 */
@Entity
@Table(name="emd_categoria"
    ,catalog="db_joao_almeida"
)
public class EmdCategoria  implements java.io.Serializable {


     private Integer emdIdCategoria;
     private String emdNomeCategoria;
     private String emdDescricao;
     private int emdVeiculosDisponiveis;
     private String emdTipoMotor;
     private String emdTurbo;
     private Date emdDataCriacao;
     private Set emdProdutos = new HashSet(0);

    public EmdCategoria() {
    }

	
    public EmdCategoria(String emdNomeCategoria, String emdDescricao, int emdVeiculosDisponiveis, String emdTipoMotor, String emdTurbo) {
        this.emdNomeCategoria = emdNomeCategoria;
        this.emdDescricao = emdDescricao;
        this.emdVeiculosDisponiveis = emdVeiculosDisponiveis;
        this.emdTipoMotor = emdTipoMotor;
        this.emdTurbo = emdTurbo;
    }
    public EmdCategoria(String emdNomeCategoria, String emdDescricao, int emdVeiculosDisponiveis, String emdTipoMotor, String emdTurbo, Date emdDataCriacao, Set emdProdutos) {
       this.emdNomeCategoria = emdNomeCategoria;
       this.emdDescricao = emdDescricao;
       this.emdVeiculosDisponiveis = emdVeiculosDisponiveis;
       this.emdTipoMotor = emdTipoMotor;
       this.emdTurbo = emdTurbo;
       this.emdDataCriacao = emdDataCriacao;
       this.emdProdutos = emdProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="emd_id_categoria", unique=true, nullable=false)
    public Integer getEmdIdCategoria() {
        return this.emdIdCategoria;
    }
    
    public void setEmdIdCategoria(Integer emdIdCategoria) {
        this.emdIdCategoria = emdIdCategoria;
    }

    
    @Column(name="emd_nome_categoria", nullable=false, length=50)
    public String getEmdNomeCategoria() {
        return this.emdNomeCategoria;
    }
    
    public void setEmdNomeCategoria(String emdNomeCategoria) {
        this.emdNomeCategoria = emdNomeCategoria;
    }

    
    @Column(name="emd_descricao", nullable=false, length=200)
    public String getEmdDescricao() {
        return this.emdDescricao;
    }
    
    public void setEmdDescricao(String emdDescricao) {
        this.emdDescricao = emdDescricao;
    }

    
    @Column(name="emd_veiculos_disponiveis", nullable=false)
    public int getEmdVeiculosDisponiveis() {
        return this.emdVeiculosDisponiveis;
    }
    
    public void setEmdVeiculosDisponiveis(int emdVeiculosDisponiveis) {
        this.emdVeiculosDisponiveis = emdVeiculosDisponiveis;
    }

    
    @Column(name="emd_tipo_motor", nullable=false, length=10)
    public String getEmdTipoMotor() {
        return this.emdTipoMotor;
    }
    
    public void setEmdTipoMotor(String emdTipoMotor) {
        this.emdTipoMotor = emdTipoMotor;
    }

    
    @Column(name="emd_turbo", nullable=false, length=10)
    public String getEmdTurbo() {
        return this.emdTurbo;
    }
    
    public void setEmdTurbo(String emdTurbo) {
        this.emdTurbo = emdTurbo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="emd_data_criacao", length=10)
    public Date getEmdDataCriacao() {
        return this.emdDataCriacao;
    }
    
    public void setEmdDataCriacao(Date emdDataCriacao) {
        this.emdDataCriacao = emdDataCriacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emdCategoria")
    public Set getEmdProdutos() {
        return this.emdProdutos;
    }
    
    public void setEmdProdutos(Set emdProdutos) {
        this.emdProdutos = emdProdutos;
    }




}


