package bean;
// Generated 15/12/2024 20:30:31 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmdCategoria generated by hbm2java
 */
@Entity
@Table(name = "emd_categoria",
         catalog = "db_joao_almeida"
)
public class EmdCategoria implements java.io.Serializable {

    private int emdIdCategoria;
    private String emdNomeCategoria;
    private String emdDescricao;
    private int emdVeiculosDisponiveis;
    private String emdTipoMotor;
    private String emdTurbo;
    private Date emdDataCriacao;

    public EmdCategoria() {
    }

    public EmdCategoria(String emdNomeCategoria, String emdDescricao, int emdVeiculosDisponiveis, String emdTipoMotor, String emdTurbo) {
        this.emdNomeCategoria = emdNomeCategoria;
        this.emdDescricao = emdDescricao;
        this.emdVeiculosDisponiveis = emdVeiculosDisponiveis;
        this.emdTipoMotor = emdTipoMotor;
        this.emdTurbo = emdTurbo;
    }

    public EmdCategoria(String emdNomeCategoria, String emdDescricao, int emdVeiculosDisponiveis, String emdTipoMotor, String emdTurbo, Date emdDataCriacao) {
        this.emdNomeCategoria = emdNomeCategoria;
        this.emdDescricao = emdDescricao;
        this.emdVeiculosDisponiveis = emdVeiculosDisponiveis;
        this.emdTipoMotor = emdTipoMotor;
        this.emdTurbo = emdTurbo;
        this.emdDataCriacao = emdDataCriacao;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "emd_id_categoria", unique = true, nullable = false)
    public Integer getEmdIdCategoria() {
        return this.emdIdCategoria;
    }

    public void setEmdIdCategoria(Integer emdIdCategoria) {
        this.emdIdCategoria = emdIdCategoria;
    }

    @Column(name = "emd_nome_categoria", nullable = false, length = 50)
    public String getEmdNomeCategoria() {
        return this.emdNomeCategoria;
    }

    public void setEmdNomeCategoria(String emdNomeCategoria) {
        this.emdNomeCategoria = emdNomeCategoria;
    }

    @Column(name = "emd_descricao", nullable = false, length = 200)
    public String getEmdDescricao() {
        return this.emdDescricao;
    }

    public void setEmdDescricao(String emdDescricao) {
        this.emdDescricao = emdDescricao;
    }

    @Column(name = "emd_veiculos_disponiveis", nullable = false)
    public int getEmdVeiculosDisponiveis() {
        return this.emdVeiculosDisponiveis;
    }

    public void setEmdVeiculosDisponiveis(int emdVeiculosDisponiveis) {
        this.emdVeiculosDisponiveis = emdVeiculosDisponiveis;
    }

    @Column(name = "emd_tipo_motor", nullable = false, length = 10)
    public String getEmdTipoMotor() {
        return this.emdTipoMotor;
    }

    public void setEmdTipoMotor(String emdTipoMotor) {
        this.emdTipoMotor = emdTipoMotor;
    }

    @Column(name = "emd_turbo", nullable = false, length = 10)
    public String getEmdTurbo() {
        return this.emdTurbo;
    }

    public void setEmdTurbo(String emdTurbo) {
        this.emdTurbo = emdTurbo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "emd_data_criacao", length = 10)
    public Date getEmdDataCriacao() {
        return this.emdDataCriacao;
    }

    public void setEmdDataCriacao(Date emdDataCriacao) {
        this.emdDataCriacao = emdDataCriacao;
    }

    @Override
    public String toString() {
        return this.emdIdCategoria + " - " + this.emdNomeCategoria;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof JvlUsuarios) {
            EmdCategoria categoria = (EmdCategoria) object;
            if (categoria.getEmdIdCategoria() == this.getEmdIdCategoria()) {
                return true;
            }
        }
        return false;
    }
}
