package bean;
// Generated 15/12/2024 20:30:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmdProduto generated by hbm2java
 */
@Entity
@Table(name="emd_produto"
    ,catalog="db_joao_almeida"
)
public class EmdProduto  implements java.io.Serializable {


     private int emdIdProduto;
     private EmdCategoria emdCategoria;
     private String emdNome;
     private double emdPreco;
     private String emdDescricao;
     private String emdCor;
     private String emdModelo;
     private String emdImagemPrincipal;
     

    public EmdProduto() {
    }

	
    public EmdProduto(int emdIdProduto, String emdNome, double emdPreco, String emdDescricao, String emdCor, String emdModelo, String emdImagemPrincipal) {
        this.emdIdProduto = emdIdProduto;
        this.emdNome = emdNome;
        this.emdPreco = emdPreco;
        this.emdDescricao = emdDescricao;
        this.emdCor = emdCor;
        this.emdModelo = emdModelo;
        this.emdImagemPrincipal = emdImagemPrincipal;
    }
    public EmdProduto(int emdIdProduto, EmdCategoria emdCategoria, String emdNome, double emdPreco, String emdDescricao, String emdCor, String emdModelo, String emdImagemPrincipal) {
       this.emdIdProduto = emdIdProduto;
       this.emdCategoria = emdCategoria;
       this.emdNome = emdNome;
       this.emdPreco = emdPreco;
       this.emdDescricao = emdDescricao;
       this.emdCor = emdCor;
       this.emdModelo = emdModelo;
       this.emdImagemPrincipal = emdImagemPrincipal;
     
    }
   
     @Id 

    
    @Column(name="emd_id_produto", unique=true, nullable=false)
    public int getEmdIdProduto() {
        return this.emdIdProduto;
    }
    
    public void setEmdIdProduto(int emdIdProduto) {
        this.emdIdProduto = emdIdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emd_id_categoria")
    public EmdCategoria getEmdCategoria() {
        return this.emdCategoria;
    }
    
    public void setEmdCategoria(EmdCategoria emdCategoria) {
        this.emdCategoria = emdCategoria;
    }

    
    @Column(name="emd_nome", nullable=false, length=30)
    public String getEmdNome() {
        return this.emdNome;
    }
    
    public void setEmdNome(String emdNome) {
        this.emdNome = emdNome;
    }

    
    @Column(name="emd_preco", nullable=false, precision=10)
    public double getEmdPreco() {
        return this.emdPreco;
    }
    
    public void setEmdPreco(double emdPreco) {
        this.emdPreco = emdPreco;
    }

    
    @Column(name="emd_descricao", nullable=false, length=200)
    public String getEmdDescricao() {
        return this.emdDescricao;
    }
    
    public void setEmdDescricao(String emdDescricao) {
        this.emdDescricao = emdDescricao;
    }

    
    @Column(name="emd_cor", nullable=false, length=30)
    public String getEmdCor() {
        return this.emdCor;
    }
    
    public void setEmdCor(String emdCor) {
        this.emdCor = emdCor;
    }

    
    @Column(name="emd_modelo", nullable=false, length=30)
    public String getEmdModelo() {
        return this.emdModelo;
    }
    
    public void setEmdModelo(String emdModelo) {
        this.emdModelo = emdModelo;
    }

    
    @Column(name="emd_imagem_principal", nullable=false, length=400)
    public String getEmdImagemPrincipal() {
        return this.emdImagemPrincipal;
    }
    
    public void setEmdImagemPrincipal(String emdImagemPrincipal) {
        this.emdImagemPrincipal = emdImagemPrincipal;
    }



}


