package bean;
// Generated 16/12/2024 18:34:19 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmdVenda generated by hbm2java
 */
@Entity
@Table(name="emd_venda"
    ,catalog="db_joao_almeida"
)
public class EmdVenda  implements java.io.Serializable {


     private int emdIdVenda;
     private EmdCliente emdCliente;
     private JvlVendedor jvlVendedor;
     private Date emdDataVenda;
     private double emdPreco;

    public EmdVenda() {
    }

	
    public EmdVenda(int emdIdVenda, EmdCliente emdCliente, JvlVendedor jvlVendedor, double emdPreco) {
        this.emdIdVenda = emdIdVenda;
        this.emdCliente = emdCliente;
        this.jvlVendedor = jvlVendedor;
        this.emdPreco = emdPreco;
    }
    public EmdVenda(int emdIdVenda, EmdCliente emdCliente, JvlVendedor jvlVendedor, Date emdDataVenda, double emdPreco) {
       this.emdIdVenda = emdIdVenda;
       this.emdCliente = emdCliente;
       this.jvlVendedor = jvlVendedor;
       this.emdDataVenda = emdDataVenda;
       this.emdPreco = emdPreco;
    }
   
     @Id 

    
    @Column(name="emd_id_venda", unique=true, nullable=false)
    public int getEmdIdVenda() {
        return this.emdIdVenda;
    }
    
    public void setEmdIdVenda(int emdIdVenda) {
        this.emdIdVenda = emdIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente", nullable=false)
    public EmdCliente getEmdCliente() {
        return this.emdCliente;
    }
    
    public void setEmdCliente(EmdCliente emdCliente) {
        this.emdCliente = emdCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendedor", nullable=false)
    public JvlVendedor getJvlVendedor() {
        return this.jvlVendedor;
    }
    
    public void setJvlVendedor(JvlVendedor jvlVendedor) {
        this.jvlVendedor = jvlVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="emd_data_venda", length=10)
    public Date getEmdDataVenda() {
        return this.emdDataVenda;
    }
    
    public void setEmdDataVenda(Date emdDataVenda) {
        this.emdDataVenda = emdDataVenda;
    }

    
    @Column(name="emd_preco", nullable=false, precision=10)
    public double getEmdPreco() {
        return this.emdPreco;
    }
    
    public void setEmdPreco(double emdPreco) {
        this.emdPreco = emdPreco;
    }


}


