package bean;
// Generated 09/12/2024 16:12:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmdVendaProdutoId generated by hbm2java
 */
@Embeddable
public class EmdVendaProdutoId  implements java.io.Serializable {


     private int emdVendaIdVenda;
     private int emdProdutoIdProduto;

    public EmdVendaProdutoId() {
    }

    public EmdVendaProdutoId(int emdVendaIdVenda, int emdProdutoIdProduto) {
       this.emdVendaIdVenda = emdVendaIdVenda;
       this.emdProdutoIdProduto = emdProdutoIdProduto;
    }
   


    @Column(name="emd_venda_id_venda", nullable=false)
    public int getEmdVendaIdVenda() {
        return this.emdVendaIdVenda;
    }
    
    public void setEmdVendaIdVenda(int emdVendaIdVenda) {
        this.emdVendaIdVenda = emdVendaIdVenda;
    }


    @Column(name="emd_produto_id_produto", nullable=false)
    public int getEmdProdutoIdProduto() {
        return this.emdProdutoIdProduto;
    }
    
    public void setEmdProdutoIdProduto(int emdProdutoIdProduto) {
        this.emdProdutoIdProduto = emdProdutoIdProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmdVendaProdutoId) ) return false;
		 EmdVendaProdutoId castOther = ( EmdVendaProdutoId ) other; 
         
		 return (this.getEmdVendaIdVenda()==castOther.getEmdVendaIdVenda())
 && (this.getEmdProdutoIdProduto()==castOther.getEmdProdutoIdProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmdVendaIdVenda();
         result = 37 * result + this.getEmdProdutoIdProduto();
         return result;
   }   


}


