package bean;
// Generated 09/12/2024 16:12:03 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmdVendaProduto generated by hbm2java
 */
@Entity
@Table(name="emd_venda_produto"
    ,catalog="db_joao_almeida"
)
public class EmdVendaProduto  implements java.io.Serializable {


     private EmdVendaProdutoId id;
     private EmdProduto emdProduto;
     private EmdVenda emdVenda;
     private int emdQuantidade;
     private double emdValorUnitario;

    public EmdVendaProduto() {
    }

    public EmdVendaProduto(EmdVendaProdutoId id, EmdProduto emdProduto, EmdVenda emdVenda, int emdQuantidade, double emdValorUnitario) {
       this.id = id;
       this.emdProduto = emdProduto;
       this.emdVenda = emdVenda;
       this.emdQuantidade = emdQuantidade;
       this.emdValorUnitario = emdValorUnitario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="emdVendaIdVenda", column=@Column(name="emd_venda_id_venda", nullable=false) ), 
        @AttributeOverride(name="emdProdutoIdProduto", column=@Column(name="emd_produto_id_produto", nullable=false) ) } )
    public EmdVendaProdutoId getId() {
        return this.id;
    }
    
    public void setId(EmdVendaProdutoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emd_produto_id_produto", nullable=false, insertable=false, updatable=false)
    public EmdProduto getEmdProduto() {
        return this.emdProduto;
    }
    
    public void setEmdProduto(EmdProduto emdProduto) {
        this.emdProduto = emdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emd_venda_id_venda", nullable=false, insertable=false, updatable=false)
    public EmdVenda getEmdVenda() {
        return this.emdVenda;
    }
    
    public void setEmdVenda(EmdVenda emdVenda) {
        this.emdVenda = emdVenda;
    }

    
    @Column(name="emd_quantidade", nullable=false)
    public int getEmdQuantidade() {
        return this.emdQuantidade;
    }
    
    public void setEmdQuantidade(int emdQuantidade) {
        this.emdQuantidade = emdQuantidade;
    }

    
    @Column(name="emd_valor_unitario", nullable=false, precision=10)
    public double getEmdValorUnitario() {
        return this.emdValorUnitario;
    }
    
    public void setEmdValorUnitario(double emdValorUnitario) {
        this.emdValorUnitario = emdValorUnitario;
    }




}


