package bean;
// Generated 16/12/2024 18:34:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmdVendaProduto generated by hbm2java
 */
@Entity
@Table(name="emd_venda_produto"
    ,catalog="db_joao_almeida"
)
public class EmdVendaProduto  implements java.io.Serializable {


     private int idVendaProduto;
     private EmdProduto emdProduto;
     private EmdVenda emdVenda;
     private String quantidade;
     private double valorUnit;

    public EmdVendaProduto() {
    }

	
    public EmdVendaProduto(int idVendaProduto, EmdProduto emdProduto, EmdVenda emdVenda) {
        this.idVendaProduto = idVendaProduto;
        this.emdProduto = emdProduto;
        this.emdVenda = emdVenda;
    }
    public EmdVendaProduto(int idVendaProduto, EmdProduto emdProduto, EmdVenda emdVenda, String quantidade, double valorUnit) {
       this.idVendaProduto = idVendaProduto;
       this.emdProduto = emdProduto;
       this.emdVenda = emdVenda;
       this.quantidade = quantidade;
       this.valorUnit = valorUnit;
    }
   
     @Id 

    
    @Column(name="id_venda_produto", unique=true, nullable=false)
    public int getIdVendaProduto() {
        return this.idVendaProduto;
    }
    
    public void setIdVendaProduto(int idVendaProduto) {
        this.idVendaProduto = idVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_produto", nullable=false)
    public EmdProduto getEmdProduto() {
        return this.emdProduto;
    }
    
    public void setEmdProduto(EmdProduto emdProduto) {
        this.emdProduto = emdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_venda", nullable=false)
    public EmdVenda getEmdVenda() {
        return this.emdVenda;
    }
    
    public void setEmdVenda(EmdVenda emdVenda) {
        this.emdVenda = emdVenda;
    }

    
    @Column(name="quantidade", length=10)
    public String getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }

    



}


