package bean;
// Generated 09/12/2024 16:12:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JvlAvaliacaoProduto generated by hbm2java
 */
@Entity
@Table(name="jvl_avaliacao_produto"
    ,catalog="db_joao_almeida"
)
public class JvlAvaliacaoProduto  implements java.io.Serializable {


     private int jvlIdAvaliacaoProduto;
     private EmdCliente emdCliente;
     private String jvlPontuacao;
     private String jvlComentario;
     private Date jvlDataAvaliacao;
     private String recomendado;
     private String tempoDeUso;
     private String informacoesAdicionais;

    public JvlAvaliacaoProduto() {
    }

	
    public JvlAvaliacaoProduto(int jvlIdAvaliacaoProduto, String jvlPontuacao, String jvlComentario, String recomendado, String tempoDeUso, String informacoesAdicionais) {
        this.jvlIdAvaliacaoProduto = jvlIdAvaliacaoProduto;
        this.jvlPontuacao = jvlPontuacao;
        this.jvlComentario = jvlComentario;
        this.recomendado = recomendado;
        this.tempoDeUso = tempoDeUso;
        this.informacoesAdicionais = informacoesAdicionais;
    }
    public JvlAvaliacaoProduto(int jvlIdAvaliacaoProduto, EmdCliente emdCliente, String jvlPontuacao, String jvlComentario, Date jvlDataAvaliacao, String recomendado, String tempoDeUso, String informacoesAdicionais) {
       this.jvlIdAvaliacaoProduto = jvlIdAvaliacaoProduto;
       this.emdCliente = emdCliente;
       this.jvlPontuacao = jvlPontuacao;
       this.jvlComentario = jvlComentario;
       this.jvlDataAvaliacao = jvlDataAvaliacao;
       this.recomendado = recomendado;
       this.tempoDeUso = tempoDeUso;
       this.informacoesAdicionais = informacoesAdicionais;
    }
   
     @Id 

    
    @Column(name="jvl_id_avaliacao_produto", unique=true, nullable=false)
    public int getJvlIdAvaliacaoProduto() {
        return this.jvlIdAvaliacaoProduto;
    }
    
    public void setJvlIdAvaliacaoProduto(int jvlIdAvaliacaoProduto) {
        this.jvlIdAvaliacaoProduto = jvlIdAvaliacaoProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_emd_id_cliente")
    public EmdCliente getEmdCliente() {
        return this.emdCliente;
    }
    
    public void setEmdCliente(EmdCliente emdCliente) {
        this.emdCliente = emdCliente;
    }

    
    @Column(name="jvl_pontuacao", nullable=false, length=15)
    public String getJvlPontuacao() {
        return this.jvlPontuacao;
    }
    
    public void setJvlPontuacao(String jvlPontuacao) {
        this.jvlPontuacao = jvlPontuacao;
    }

    
    @Column(name="jvl_comentario", nullable=false, length=500)
    public String getJvlComentario() {
        return this.jvlComentario;
    }
    
    public void setJvlComentario(String jvlComentario) {
        this.jvlComentario = jvlComentario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jvl_data_avaliacao", length=10)
    public Date getJvlDataAvaliacao() {
        return this.jvlDataAvaliacao;
    }
    
    public void setJvlDataAvaliacao(Date jvlDataAvaliacao) {
        this.jvlDataAvaliacao = jvlDataAvaliacao;
    }

    
    @Column(name="recomendado", nullable=false, length=20)
    public String getRecomendado() {
        return this.recomendado;
    }
    
    public void setRecomendado(String recomendado) {
        this.recomendado = recomendado;
    }

    
    @Column(name="tempo_de_uso", nullable=false, length=50)
    public String getTempoDeUso() {
        return this.tempoDeUso;
    }
    
    public void setTempoDeUso(String tempoDeUso) {
        this.tempoDeUso = tempoDeUso;
    }

    
    @Column(name="informacoes_adicionais", nullable=false, length=500)
    public String getInformacoesAdicionais() {
        return this.informacoesAdicionais;
    }
    
    public void setInformacoesAdicionais(String informacoesAdicionais) {
        this.informacoesAdicionais = informacoesAdicionais;
    }


}


