package bean;
// Generated 07/12/2024 15:09:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JvlCompraProduto generated by hbm2java
 */
@Entity
@Table(name="jvl_compra_produto"
    ,catalog="db_joao_almeida"
)
public class JvlCompraProduto  implements java.io.Serializable {


     private Integer jvlIdCompraProduto;
     private EmdProduto emdProduto;
     private JvlCompra jvlCompra;
     private int emdQuantidade;
     private BigDecimal emdPrecoUnitario;

    public JvlCompraProduto() {
    }

    public JvlCompraProduto(EmdProduto emdProduto, JvlCompra jvlCompra, int emdQuantidade, BigDecimal emdPrecoUnitario) {
       this.emdProduto = emdProduto;
       this.jvlCompra = jvlCompra;
       this.emdQuantidade = emdQuantidade;
       this.emdPrecoUnitario = emdPrecoUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jvl_id_compra_produto", unique=true, nullable=false)
    public Integer getJvlIdCompraProduto() {
        return this.jvlIdCompraProduto;
    }
    
    public void setJvlIdCompraProduto(Integer jvlIdCompraProduto) {
        this.jvlIdCompraProduto = jvlIdCompraProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_jvl_id_produto", nullable=false)
    public EmdProduto getEmdProduto() {
        return this.emdProduto;
    }
    
    public void setEmdProduto(EmdProduto emdProduto) {
        this.emdProduto = emdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra_jvl_id_compra", nullable=false)
    public JvlCompra getJvlCompra() {
        return this.jvlCompra;
    }
    
    public void setJvlCompra(JvlCompra jvlCompra) {
        this.jvlCompra = jvlCompra;
    }

    
    @Column(name="emd_quantidade", nullable=false)
    public int getEmdQuantidade() {
        return this.emdQuantidade;
    }
    
    public void setEmdQuantidade(int emdQuantidade) {
        this.emdQuantidade = emdQuantidade;
    }

    
    @Column(name="emd_preco_unitario", nullable=false, precision=10)
    public BigDecimal getEmdPrecoUnitario() {
        return this.emdPrecoUnitario;
    }
    
    public void setEmdPrecoUnitario(BigDecimal emdPrecoUnitario) {
        this.emdPrecoUnitario = emdPrecoUnitario;
    }




}


