package bean;
// Generated 09/12/2024 16:12:03 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JvlCompraProduto generated by hbm2java
 */
@Entity
@Table(name="jvl_compra_produto"
    ,catalog="db_joao_almeida"
)
public class JvlCompraProduto  implements java.io.Serializable {


     private int jvlIdCompraProduto;
     private EmdProduto emdProduto;
     private JvlCompra jvlCompra;
     private int emdQuantidade;
     private double emdPrecoUnitario;

    public JvlCompraProduto() {
    }

	
    public JvlCompraProduto(int jvlIdCompraProduto, int emdQuantidade, double emdPrecoUnitario) {
        this.jvlIdCompraProduto = jvlIdCompraProduto;
        this.emdQuantidade = emdQuantidade;
        this.emdPrecoUnitario = emdPrecoUnitario;
    }
    public JvlCompraProduto(int jvlIdCompraProduto, EmdProduto emdProduto, JvlCompra jvlCompra, int emdQuantidade, double emdPrecoUnitario) {
       this.jvlIdCompraProduto = jvlIdCompraProduto;
       this.emdProduto = emdProduto;
       this.jvlCompra = jvlCompra;
       this.emdQuantidade = emdQuantidade;
       this.emdPrecoUnitario = emdPrecoUnitario;
    }
   
     @Id 

    
    @Column(name="jvl_id_compra_produto", unique=true, nullable=false)
    public int getJvlIdCompraProduto() {
        return this.jvlIdCompraProduto;
    }
    
    public void setJvlIdCompraProduto(int jvlIdCompraProduto) {
        this.jvlIdCompraProduto = jvlIdCompraProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_jvl_id_produto")
    public EmdProduto getEmdProduto() {
        return this.emdProduto;
    }
    
    public void setEmdProduto(EmdProduto emdProduto) {
        this.emdProduto = emdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra_jvl_id_compra")
    public JvlCompra getJvlCompra() {
        return this.jvlCompra;
    }
    
    public void setJvlCompra(JvlCompra jvlCompra) {
        this.jvlCompra = jvlCompra;
    }

    
    @Column(name="emd_quantidade", nullable=false)
    public int getEmdQuantidade() {
        return this.emdQuantidade;
    }
    
    public void setEmdQuantidade(int emdQuantidade) {
        this.emdQuantidade = emdQuantidade;
    }

    
    @Column(name="emd_preco_unitario", nullable=false, precision=10)
    public double getEmdPrecoUnitario() {
        return this.emdPrecoUnitario;
    }
    
    public void setEmdPrecoUnitario(double emdPrecoUnitario) {
        this.emdPrecoUnitario = emdPrecoUnitario;
    }




}


