package bean;
// Generated 14/12/2024 11:25:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JvlCompra generated by hbm2java
 */
@Entity
@Table(name="jvl_compra"
    ,catalog="db_joao_almeida"
)
public class JvlCompra  implements java.io.Serializable {


     private int jvlIdCompra;
     private JvlFornecedor jvlFornecedor;
     private JvlUsuarios jvlUsuarios;
     private Date jvlDataCompra;
     private BigDecimal jvlValorTotal;
     private Set compraProdutos = new HashSet(0);

    public JvlCompra() {
    }

	
    public JvlCompra(int jvlIdCompra, JvlFornecedor jvlFornecedor, JvlUsuarios jvlUsuarios, BigDecimal jvlValorTotal) {
        this.jvlIdCompra = jvlIdCompra;
        this.jvlFornecedor = jvlFornecedor;
        this.jvlUsuarios = jvlUsuarios;
        this.jvlValorTotal = jvlValorTotal;
    }
    public JvlCompra(int jvlIdCompra, JvlFornecedor jvlFornecedor, JvlUsuarios jvlUsuarios, Date jvlDataCompra, BigDecimal jvlValorTotal, Set compraProdutos) {
       this.jvlIdCompra = jvlIdCompra;
       this.jvlFornecedor = jvlFornecedor;
       this.jvlUsuarios = jvlUsuarios;
       this.jvlDataCompra = jvlDataCompra;
       this.jvlValorTotal = jvlValorTotal;
       this.compraProdutos = compraProdutos;
    }
   
     @Id 

    
    @Column(name="jvl_id_compra", unique=true, nullable=false)
    public int getJvlIdCompra() {
        return this.jvlIdCompra;
    }
    
    public void setJvlIdCompra(int jvlIdCompra) {
        this.jvlIdCompra = jvlIdCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_fornecedor", nullable=false)
    public JvlFornecedor getJvlFornecedor() {
        return this.jvlFornecedor;
    }
    
    public void setJvlFornecedor(JvlFornecedor jvlFornecedor) {
        this.jvlFornecedor = jvlFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_usuarios", nullable=false)
    public JvlUsuarios getJvlUsuarios() {
        return this.jvlUsuarios;
    }
    
    public void setJvlUsuarios(JvlUsuarios jvlUsuarios) {
        this.jvlUsuarios = jvlUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jvl_data_compra", length=10)
    public Date getJvlDataCompra() {
        return this.jvlDataCompra;
    }
    
    public void setJvlDataCompra(Date jvlDataCompra) {
        this.jvlDataCompra = jvlDataCompra;
    }

    
    @Column(name="jvl_valor_total", nullable=false, precision=10)
    public BigDecimal getJvlValorTotal() {
        return this.jvlValorTotal;
    }
    
    public void setJvlValorTotal(BigDecimal jvlValorTotal) {
        this.jvlValorTotal = jvlValorTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jvlCompra")
    public Set getCompraProdutos() {
        return this.compraProdutos;
    }
    
    public void setCompraProdutos(Set compraProdutos) {
        this.compraProdutos = compraProdutos;
    }




}


