package bean;
// Generated 07/12/2024 15:09:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JvlUsuario generated by hbm2java
 */
@Entity
@Table(name="jvl_usuario"
    ,catalog="db_joao_almeida"
)
public class JvlUsuario  implements java.io.Serializable {


     private Integer jvlIdUsuario;
     private String jvlNome;
     private String jvlApelido;
     private String jvlCpf;
     private Date jvlDataNascimento;
     private String jvlSenha;
     private int jvlNivel;
     private String jvlAtivo;
     private Set emdVendas = new HashSet(0);

    public JvlUsuario() {
    }

	
    public JvlUsuario(String jvlNome, String jvlApelido, String jvlCpf, String jvlSenha, int jvlNivel, String jvlAtivo) {
        this.jvlNome = jvlNome;
        this.jvlApelido = jvlApelido;
        this.jvlCpf = jvlCpf;
        this.jvlSenha = jvlSenha;
        this.jvlNivel = jvlNivel;
        this.jvlAtivo = jvlAtivo;
    }
    public JvlUsuario(String jvlNome, String jvlApelido, String jvlCpf, Date jvlDataNascimento, String jvlSenha, int jvlNivel, String jvlAtivo, Set emdVendas) {
       this.jvlNome = jvlNome;
       this.jvlApelido = jvlApelido;
       this.jvlCpf = jvlCpf;
       this.jvlDataNascimento = jvlDataNascimento;
       this.jvlSenha = jvlSenha;
       this.jvlNivel = jvlNivel;
       this.jvlAtivo = jvlAtivo;
       this.emdVendas = emdVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jvl_id_usuario", unique=true, nullable=false)
    public Integer getJvlIdUsuario() {
        return this.jvlIdUsuario;
    }
    
    public void setJvlIdUsuario(Integer jvlIdUsuario) {
        this.jvlIdUsuario = jvlIdUsuario;
    }

    
    @Column(name="jvl_nome", nullable=false, length=50)
    public String getJvlNome() {
        return this.jvlNome;
    }
    
    public void setJvlNome(String jvlNome) {
        this.jvlNome = jvlNome;
    }

    
    @Column(name="jvl_apelido", nullable=false, length=25)
    public String getJvlApelido() {
        return this.jvlApelido;
    }
    
    public void setJvlApelido(String jvlApelido) {
        this.jvlApelido = jvlApelido;
    }

    
    @Column(name="jvl_cpf", nullable=false, length=14)
    public String getJvlCpf() {
        return this.jvlCpf;
    }
    
    public void setJvlCpf(String jvlCpf) {
        this.jvlCpf = jvlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jvl_dataNascimento", length=10)
    public Date getJvlDataNascimento() {
        return this.jvlDataNascimento;
    }
    
    public void setJvlDataNascimento(Date jvlDataNascimento) {
        this.jvlDataNascimento = jvlDataNascimento;
    }

    
    @Column(name="jvl_senha", nullable=false, length=20)
    public String getJvlSenha() {
        return this.jvlSenha;
    }
    
    public void setJvlSenha(String jvlSenha) {
        this.jvlSenha = jvlSenha;
    }

    
    @Column(name="jvl_nivel", nullable=false)
    public int getJvlNivel() {
        return this.jvlNivel;
    }
    
    public void setJvlNivel(int jvlNivel) {
        this.jvlNivel = jvlNivel;
    }

    
    @Column(name="jvl_ativo", nullable=false, length=1)
    public String getJvlAtivo() {
        return this.jvlAtivo;
    }
    
    public void setJvlAtivo(String jvlAtivo) {
        this.jvlAtivo = jvlAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jvlUsuario")
    public Set getEmdVendas() {
        return this.emdVendas;
    }
    
    public void setEmdVendas(Set emdVendas) {
        this.emdVendas = emdVendas;
    }




}


