package bean;
// Generated 15/12/2024 20:30:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JvlUsuarios generated by hbm2java
 */
@Entity
@Table(name="jvl_usuarios"
    ,catalog="db_joao_almeida"
)
public class JvlUsuarios  implements java.io.Serializable {


     private int jvlIdUsuarios;
     private String jvlNome;
     private String jvlApelido;
     private String jvlCpf;
     private Date jvlNascimento;
     private String jvlSenha;
     private int jvlNivel;
     private String jvlAtivo;

    public JvlUsuarios() {
    }

	
    public JvlUsuarios(int jvlIdUsuarios, String jvlNome, String jvlApelido, String jvlCpf, String jvlSenha, int jvlNivel, String jvlAtivo) {
        this.jvlIdUsuarios = jvlIdUsuarios;
        this.jvlNome = jvlNome;
        this.jvlApelido = jvlApelido;
        this.jvlCpf = jvlCpf;
        this.jvlSenha = jvlSenha;
        this.jvlNivel = jvlNivel;
        this.jvlAtivo = jvlAtivo;
    }
    public JvlUsuarios(int jvlIdUsuarios, String jvlNome, String jvlApelido, String jvlCpf, Date jvlNascimento, String jvlSenha, int jvlNivel, String jvlAtivo) {
       this.jvlIdUsuarios = jvlIdUsuarios;
       this.jvlNome = jvlNome;
       this.jvlApelido = jvlApelido;
       this.jvlCpf = jvlCpf;
       this.jvlNascimento = jvlNascimento;
       this.jvlSenha = jvlSenha;
       this.jvlNivel = jvlNivel;
       this.jvlAtivo = jvlAtivo;
    }
   
     @Id 

    
    @Column(name="jvl_id_usuarios", unique=true, nullable=false)
    public int getJvlIdUsuarios() {
        return this.jvlIdUsuarios;
    }
    
    public void setJvlIdUsuarios(int jvlIdUsuarios) {
        this.jvlIdUsuarios = jvlIdUsuarios;
    }

    
    @Column(name="jvl_nome", nullable=false, length=70)
    public String getJvlNome() {
        return this.jvlNome;
    }
    
    public void setJvlNome(String jvlNome) {
        this.jvlNome = jvlNome;
    }

    
    @Column(name="jvl_apelido", nullable=false, length=20)
    public String getJvlApelido() {
        return this.jvlApelido;
    }
    
    public void setJvlApelido(String jvlApelido) {
        this.jvlApelido = jvlApelido;
    }

    
    @Column(name="jvl_cpf", nullable=false, length=14)
    public String getJvlCpf() {
        return this.jvlCpf;
    }
    
    public void setJvlCpf(String jvlCpf) {
        this.jvlCpf = jvlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jvl_nascimento", length=10)
    public Date getJvlNascimento() {
        return this.jvlNascimento;
    }
    
    public void setJvlNascimento(Date jvlNascimento) {
        this.jvlNascimento = jvlNascimento;
    }

    
    @Column(name="jvl_senha", nullable=false, length=40)
    public String getJvlSenha() {
        return this.jvlSenha;
    }
    
    public void setJvlSenha(String jvlSenha) {
        this.jvlSenha = jvlSenha;
    }

    
    @Column(name="jvl_nivel", nullable=false)
    public int getJvlNivel() {
        return this.jvlNivel;
    }
    
    public void setJvlNivel(int jvlNivel) {
        this.jvlNivel = jvlNivel;
    }

    
    @Column(name="jvl_ativo", nullable=false, length=2)
    public String getJvlAtivo() {
        return this.jvlAtivo;
    }
    
    public void setJvlAtivo(String jvlAtivo) {
        this.jvlAtivo = jvlAtivo;
    }



}


