package bean;
// Generated 14/12/2024 11:25:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JvlVendedor generated by hbm2java
 */
@Entity
@Table(name="jvl_vendedor"
    ,catalog="db_joao_almeida"
)
public class JvlVendedor  implements java.io.Serializable {


     private int jvlIdVendedor;
     private String jvlNome;
     private String jvlTelefone;
     private String jvlCpf;
     private int jvlGenero;
     private BigDecimal jvlSalario;
     private String jvlEmail;
     private Set emdVendas = new HashSet(0);

    public JvlVendedor() {
    }

	
    public JvlVendedor(int jvlIdVendedor, String jvlNome, String jvlCpf, int jvlGenero) {
        this.jvlIdVendedor = jvlIdVendedor;
        this.jvlNome = jvlNome;
        this.jvlCpf = jvlCpf;
        this.jvlGenero = jvlGenero;
    }
    public JvlVendedor(int jvlIdVendedor, String jvlNome, String jvlTelefone, String jvlCpf, int jvlGenero, BigDecimal jvlSalario, String jvlEmail, Set emdVendas) {
       this.jvlIdVendedor = jvlIdVendedor;
       this.jvlNome = jvlNome;
       this.jvlTelefone = jvlTelefone;
       this.jvlCpf = jvlCpf;
       this.jvlGenero = jvlGenero;
       this.jvlSalario = jvlSalario;
       this.jvlEmail = jvlEmail;
       this.emdVendas = emdVendas;
    }
   
     @Id 

    
    @Column(name="jvl_id_vendedor", unique=true, nullable=false)
    public int getJvlIdVendedor() {
        return this.jvlIdVendedor;
    }
    
    public void setJvlIdVendedor(int jvlIdVendedor) {
        this.jvlIdVendedor = jvlIdVendedor;
    }

    
    @Column(name="jvl_nome", nullable=false, length=60)
    public String getJvlNome() {
        return this.jvlNome;
    }
    
    public void setJvlNome(String jvlNome) {
        this.jvlNome = jvlNome;
    }

    
    @Column(name="jvl_telefone", length=20)
    public String getJvlTelefone() {
        return this.jvlTelefone;
    }
    
    public void setJvlTelefone(String jvlTelefone) {
        this.jvlTelefone = jvlTelefone;
    }

    
    @Column(name="jvl_cpf", nullable=false, length=14)
    public String getJvlCpf() {
        return this.jvlCpf;
    }
    
    public void setJvlCpf(String jvlCpf) {
        this.jvlCpf = jvlCpf;
    }

    
    @Column(name="jvl_genero", nullable=false)
    public int getJvlGenero() {
        return this.jvlGenero;
    }
    
    public void setJvlGenero(int jvlGenero) {
        this.jvlGenero = jvlGenero;
    }

    
    @Column(name="jvl_salario", precision=7)
    public BigDecimal getJvlSalario() {
        return this.jvlSalario;
    }
    
    public void setJvlSalario(BigDecimal jvlSalario) {
        this.jvlSalario = jvlSalario;
    }

    
    @Column(name="jvl_email", length=95)
    public String getJvlEmail() {
        return this.jvlEmail;
    }
    
    public void setJvlEmail(String jvlEmail) {
        this.jvlEmail = jvlEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jvlVendedor")
    public Set getEmdVendas() {
        return this.emdVendas;
    }
    
    public void setEmdVendas(Set emdVendas) {
        this.emdVendas = emdVendas;
    }




}


